def build_trade_dict(
    side,
    entry_ts,
    exit_ts,
    entry,
    exit_price,
    pnl,
    pnl_gross,
    fees,
    exit_reason,
    sl,
    tp,
    sl_pct,
    tp_pct,
):
    return {
        "side": side,
        "entry_ts": entry_ts,
        "exit_ts": exit_ts,
        "entry": entry,
        "exit_price": exit_price,
        "pnl": pnl,
        "pnl_gross": pnl_gross,
        "fees": fees,
        "exit_reason": exit_reason,
        "sl": round(abs(sl), 3),
        "tp": round(tp, 3),
        "sl_pct": round(sl_pct, 3),
        "tp_pct": round(tp_pct, 3),
    }
