# ====================
# ====================

SYMBOLS = [
    "BTCUSDT",
    "TRXUSDT",
    "ETCUSDT",
    "LINKUSDT",
    "XLMUSDT",
    "ADAUSDT",
    "XMRUSDT",
    "DASHUSDT",
    "ZECUSDT",
    "XTZUSDT",
    "BNBUSDT",
    "ONTUSDT",
    "IOTAUSDT",
    "INJUSDT",
    "FETUSDT",
    "TIAUSDT",
    "NEARUSDT",
    "ARBUSDT",
    "APTUSDT",
    "SUIUSDT",
    "SEIUSDT",
    "OPUSDT",
    "RAYSOLUSDT",
    "WIFUSDT",
    "ENAUSDT",
    "JUPUSDT",
    "RENDERUSDT",
    "TAOUSDT",
    "PENDLEUSDT",
    "1000BONKUSDT",
    "ATOMUSDT",
    "FILUSDT",
    "UNIUSDT",
    "AAVEUSDT",
    "HBARUSDT",
    "HYPEUSDT",
    "SKLUSDT",
    "GRTUSDT",
    "1INCHUSDT",
    "CHZUSDT",
    "SANDUSDT",
    "ANKRUSDT",
    "RVNUSDT",
    "SFPUSDT",
    "COTIUSDT",
    "CHRUSDT",
    "MANAUSDT",
    "ALICEUSDT",
    "ONDOUSDT",
    'AGLDUSDT', 
    'APEUSDT', 
    'ARCUSDT', 
    'COLLECTUSDT',
    "BICOUSDT",
    "BIGTIMEUSDT",
    "WAXPUSDT",
    "BSVUSDT",
    "RIFUSDT",
    "POLYXUSDT",
    "GASUSDT",
    "ASTERUSDT",
    "TRADOORUSDT",
    "BLESSUSDT",
    "FLUIDUSDT",
    "COAIUSDT",
    "HANAUSDT",
    "MIRAUSDT",
    "AKEUSDT",
    "ORDERUSDT",
    "LIGHTUSDT",
    "XANUSDT",
    "POWRUSDT",
    'HUMAUSDT', 
    'JSTUSDT', 
    'KITEUSDT', 
    'PAXGUSDT', 
    'QNTUSDT', 
    'SYNUSDT', 
    'USDCUSDT', 
    'VELVETUSDT', 
    'WLFIUSDT', 
    #'XAUTUSDT', 
    'ATUSDT', 
    'AWEUSDT', 
    'JELLYJELLYUSDT', 
    'KOMAUSDT', 
    'MAGMAUSDT', 
    'SAHARAUSDT', 
    'XNYUSDT',
    "QUSDT",
    "ARIAUSDT",
    "BSBUSDT",
    #"BASEDUSDT",
    #"PRLUSDT",
    #"GENIUSUSDT",
    #"CHIPUSDT",
    #"OPGUSDT",
    #"AIGENSYNUSDT",
    #"BILLUSDT",
    #"PHAROSUSDT",
    #"STARUSDT",
    #"CTRUSDT",
    "TAKEUSDT",
    "BEATUSDT",
    "PIEVERSEUSDT",
    "SENTUSDT",
    #"IRYSUSDT",
    "POWERUSDT",
    "WETUSDT",
    "NIGHTUSDT",
    "USUSDT",
    "CYSUSDT",
    "RAVEUSDT",
    "ZKPUSDT",
    "GUAUSDT",
    "LITUSDT",
    "TRUMPUSDT",
    "MELANIAUSDT",
    "VTHOUSDT",
    "ANIMEUSDT",
    "PIPPINUSDT",
    "VVVUSDT",
    "BERAUSDT",
    "TSTUSDT",
    "LAYERUSDT",
    "HEIUSDT",
    "IPUSDT",
    "GPSUSDT",
    "SHELLUSDT",
    "KAITOUSDT",
    "REDUSDT",
    "VICUSDT",
    "BREVUSDT",
    "PTBUSDT",
    #"OPENUSDT",
    "FLOCKUSDT",
    "SKYUSDT",
    "AVNTUSDT",
    "HOLOUSDT",
    "XPINUSDT",
    "ZAMAUSDT",
    "FOGOUSDT",
    "FRAXUSDT",
    "SPORTFUNUSDT",
    "AIAUSDT",
    "ACUUSDT",
    "我踏马来了USDT",
    "ELSAUSDT",
    "SKRUSDT",
    "ENSOUSDT",
    "CLOUSDT",
    "RECALLUSDT",
    "ZBTUSDT",
    "LABUSDT",
    "RIVERUSDT",
    "币安人生USDT",
    "BLUAIUSDT",
    "FFUSDT",
    "EDENUSDT",
    "NOMUSDT",
    "TRUTHUSDT",
    "2ZUSDT",
    "EVAAUSDT",
    "LYNUSDT",
    "KGENUSDT",
    "4USDT",
    "GIGGLEUSDT",
    "MONUSDT",
    "YBUSDT",
    "METUSDT",
    "EULUSDT",
    "TACUSDT",
    "ERAUSDT",
    "TAUSDT",
    "CVXUSDT",
    "SLPUSDT",
    "ZORAUSDT",
    "TAGUSDT",
    "ESPORTSUSDT",
    "TREEUSDT",
    "PLAYUSDT",
    "NAORISUSDT",
    "TOWNSUSDT",
    "PROVEUSDT",
    "ALLUSDT",
    "INUSDT",
    "CARVUSDT",
    "SUSHIUSDT",
    "RUNEUSDT",
    "CAKEUSDT",
    "GMXUSDT",
    "DYDXUSDT",
    "LDOUSDT",
    "IMXUSDT",
    "ARKMUSDT",
    "CYBERUSDT",
    "AIOTUSDT",
    "CGPTUSDT",
    "1000PEPEUSDT",
    "1000FLOKIUSDT",
    "BRETTUSDT",
    "POPCATUSDT",
    "DOGSUSDT",
    "NEIROUSDT",
    "GOATUSDT",
    "MOODENGUSDT",
    "PNUTUSDT",
    "FARTCOINUSDT",
    "TURBOUSDT",
    "MANTAUSDT",
    "AEVOUSDT",
    "ETHFIUSDT",
    "REZUSDT",
    "LISTAUSDT",
    "ZROUSDT",
    "ALTUSDT",
    "STRKUSDT",
    "PORTALUSDT",
    "METISUSDT",
    "DYMUSDT",
    "PIXELUSDT",
    "TUSDT",
    "WUSDT",
    "GUSDT",
    "DUSDT",
    "SUSDT",
    "BUSDT",
    "AUSDT",
    "FUSDT",
    "HUSDT",
    "MUSDT",
    "BUSDT",
    "QUSDT",

]

MAX_GLOBAL_POSITIONS = 3

BACKTEST = {
    "days": 100,
    "lookahead": 1,
    "warmup": 100,
}

BACKTEST_AGGRESSIVE = {
    "days": 7,
    "warmup": 5,
    "lookahead":10
}

LONG_AGGRESSIVE = {
    "sl_mult": 1.75,
    "tp_mult": 1.75,
    "min_tp": 0.31,
}

SHORT_AGGRESSIVE = {
    "sl_mult": 1.75,
    "tp_mult": 1.75,
    "min_tp": 0.25,
    "min_tp": 0.25,
}

FEES = {
    "taker": 0.05,
    "maker": 0.02,
    "funding": 0.0,
}

LONG = {
    "sl_mult": 2.0,
    "tp_mult": 1.20,
    "min_tp": 0.31,
}

SHORT = {
    "sl_mult": 2.1,
    "tp_mult": 1.60,
    "min_tp": 0.25,
}

#LONG = {
#    "sl_mult": 1.9,
#    "tp_mult": 1.38,
#    "min_tp": 0.31,
#}

#SHORT = {
#    "sl_mult": 1.9,
#    "tp_mult": 1.56,
#    "min_tp": 0.25,
#}
